project:
  type: website

website:
  title: "Infra Wiss Blogs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/infomgnt/infrawissblogs/
      - icon: twitter
        href: https://twitter.com/pampel
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

